[package]
name = "trait_sample3"
version = "0.1.0"
authors = ["nishitaniyuki <yuki-nishitani@cybozu.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
