[package]
name = "cannot_mutate_element_of_borrowed_vector"
version = "0.1.0"
authors = ["nishitaniyuki <yuki.nishitani85@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
